ALTER TYPE "ExecutionMode" ADD VALUE 'MULTI';

ALTER TABLE "UserSettings"
  ADD COLUMN "defaultSymbol" TEXT NOT NULL DEFAULT 'XAUUSD',
  ADD COLUMN "multiTradesPerSide" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN "multiFirstEntryPips" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "multiFirstSlPips" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "multiFirstTpPips" INTEGER NOT NULL DEFAULT 200,
  ADD COLUMN "multiNextStepPips" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "multiNextSlPips" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "multiNextTpPips" INTEGER NOT NULL DEFAULT 200,
  ADD COLUMN "multiExpirySeconds" INTEGER NOT NULL DEFAULT 30;

ALTER TABLE "TradeJob"
  ADD COLUMN "multiTradesPerSide" INTEGER,
  ADD COLUMN "multiNextStepPoints" INTEGER,
  ADD COLUMN "multiNextSlPoints" INTEGER,
  ADD COLUMN "multiNextTpPoints" INTEGER;
